### ISSUE TITLE
Issue running on RPI, fairseq

### ISSUE THREAD

**Issue by ciaotesla** [Vali-98/XTTS-RVC-UI#6]
I am getting this error:

`python app.py 
Traceback (most recent call last):
  File "/home/pi4/social/XTTS-RVC-UI/app.py", line 4, in <module>
    from rvc import Config, load_hubert, get_vc, rvc_infer
  File "/home/pi4/social/XTTS-RVC-UI/rvc.py", line 6, in <module>
    from fairseq import checkpoint_utils
  File "/home/pi4/social/.vsocial/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/pi4/social/.vsocial/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/home/pi4/social/.vsocial/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/home/pi4/social/.vsocial/lib/python3.11/site-packages/fairseq/dataclass/__init__.py", line 6, in <module>
    from .configs import FairseqDataclass
  File "/home/pi4/social/.vsocial/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory
`

**Comment by ciaotesla** [comment]
solution [here](https://github.com/facebookresearch/fairseq/issues/5012)
