### ISSUE TITLE
Requirements conflict

### ISSUE THREAD

**Issue by achartt** [Vali-98/XTTS-RVC-UI#8]
Having trouble getting the TTS RVC WebUI installed getting this error:

ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 12), -r requirements.txt (line 3), -r requirements.txt (line 4), -r requirements.txt (line 7), -r requirements.txt (line 9) and numpy==1.22.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.22.0
    fairseq 0.12.2 depends on numpy; python_version >= "3.7"
    gradio 4.7.1 depends on numpy~=1.0
    librosa 0.10.0 depends on numpy>=1.20.3
    pyworld 0.3.4 depends on numpy
    scipy 1.11.4 depends on numpy=1.21.6
    tts 0.21.1 depends on numpy>=1.24.3; python_version > "3.10"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by clementvp** [comment]
Can you try numpy==1.24.3 in requirement.txt. Works for me.  
But i think you have Python >3.11, you absolutely need 3.10 max ( because of the setuptools drama) app.py will not run in 3.11+

**Comment by HyperUpscale** [comment]
Python 3.10 on Windows:

The conflict is caused by:
    The user requested numpy==1.24.3
    fairseq 0.12.2 depends on numpy; python_version >= "3.7"
    gradio 4.7.1 depends on numpy~=1.0
    librosa 0.10.0 depends on numpy>=1.20.3
    pyworld 0.3.4 depends on numpy
    scipy 1.11.4 depends on numpy<1.28.0 and >=1.21.6
    tts 0.21.1 depends on numpy==1.22.0; python_version <= "3.10"

**Comment by clementvp** [comment]
In python 3.10 ( conda env) I managed to install dependencies with:

```fairseq==0.12.2
faiss_cpu==1.7.4
gradio==4.7.1
librosa==0.10.0
numpy==1.22.0
praat-parselmouth
pyworld==0.3.4
Requests==2.31.0
scipy==1.11.4
torch==2.1.0
torchcrepe==0.0.22
TTS==0.21.1
```

In requirements.txt.

**Comment by Vali-98** [comment]
I haven't touched this project in a while, but if I recall, this was done in python 3.10 and for whatever reason worked in a venv.

If I have time I'll investigate this.

**Comment by achartt** [comment]
It was python 3.11 I had 3.10 installed but in the wrong order in my environment PATH.

**Comment by TomiTom1234** [comment]
I also face this issue, the exact same error.
How can I solve this, please?

**Comment by TomiTom1234** [comment]
This is my error, exact same as the OP:
`INFO: pip is looking at multiple versions of tts to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 12), -r requirements.txt (line 3), -r requirements.txt (line 4), -r requirements.txt (line 7), -r requirements.txt (line 9) and numpy==1.22.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==1.22.0
    fairseq 0.12.2 depends on numpy; python_version >= "3.7"
    gradio 4.7.1 depends on numpy~=1.0
    librosa 0.10.0 depends on numpy>=1.20.3
    pyworld 0.3.4 depends on numpy
    scipy 1.11.4 depends on numpy<1.28.0 and >=1.21.6
    tts 0.21.1 depends on numpy>=1.24.3; python_version > "3.10"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`
Any help please how to solve it?

**Comment by steffenr** [comment]
I also run into the same issue. 
You should create a custom python environment for installing. 

The easiest way is **conda**. 

Just place a environment.yaml into the project folder with the following content:

```
name: xtts
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - packaging
```

And run the following commands

-  `conda env create -f environment.yaml` 
- `conda activate xtts`
- pip install -r requirements.txt

**Comment by TomiTom1234** [comment]
> I also run into the same issue. You should create a custom python environment for installing.
> 
> The easiest way is **conda**.
> 
> Just place a environment.yaml into the project folder with the following content:
> 
> ```
> name: xtts
> channels:
>   - defaults
> dependencies:
>   - python=3.10
>   - pip=23.0
>   - packaging
> ```
> 
> And run the following commands
> 
> * `conda env create -f environment.yaml`
> * `conda activate xtts`
> * pip install -r requirements.txt

I am a bit new with this.
Do you mean I just create a new text file then paste the following in it:

name: xtts
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - packaging
 
after that save the file under the name "environment.yaml" ? After that move it to afolder called "Project" or in the main folder of XTTS-RVC-UI ?

Then run the codes you mentioned through a command prompt (cmd) or do you mean "Anaconda" prompt?

Thank you!

**Comment by MrRaja23** [comment]
> I also run into the same issue. You should create a custom python environment for installing.
> 
> The easiest way is **conda**.
> 
> Just place a environment.yaml into the project folder with the following content:
> 
> ```
> name: xtts
> channels:
>   - defaults
> dependencies:
>   - python=3.10
>   - pip=23.0
>   - packaging
> ```
> 
> And run the following commands
> 
> * `conda env create -f environment.yaml`
> * `conda activate xtts`
> * pip install -r requirements.txt

I am running into more issues installing Conda and it not working at all:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\miniconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\Lib\site-packages\conda\cli\main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 199, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\Lib\site-packages\conda\notices\core.py", line 131, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\Lib\site-packages\conda\cli\main_env_create.py", line 112, in execute
        spec = specs.detect(
               ^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\Lib\site-packages\conda\env\specs\__init__.py", line 71, in detect
        if spec.can_handle():
           ^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\Lib\site-packages\conda\env\specs\yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\Lib\site-packages\conda\env\env.py", line 172, in from_file
        return from_yaml(yamlstr, filename=filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\Lib\site-packages\conda\env\env.py", line 142, in from_yaml
        data = validate_keys(data, kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\ProgramData\miniconda3\Lib\site-packages\conda\env\env.py", line 30, in validate_keys
        new_data = data.copy() if data else {}
                   ^^^^^^^^^
    AttributeError: 'str' object has no attribute 'copy'

**Comment by cryptotester** [comment]
> In python 3.10 ( conda env) I managed to install dependencies with:
> 
> ```
> faiss_cpu==1.7.4
> gradio==4.7.1
> librosa==0.10.0
> numpy==1.22.0
> praat-parselmouth
> pyworld==0.3.4
> Requests==2.31.0
> scipy==1.11.4
> torch==2.1.0
> torchcrepe==0.0.22
> TTS==0.21.1
> ```
> 
> In requirements.txt.

Thank you @clementvp using this list of requirements, with python 3.10 (latest: 3.10.14 now) worked fine for me (after trying the original requirements).

**Comment by jbusodev** [comment]
Similiar issue for me related to `pyworld` and `fairseq` in original `requirements.txt` : "`Cannot build wheel for pyworld`".

**Comment by SiddhantStark** [comment]
Getting this error:

ERROR: Cannot install -r requirements.txt (line 1) and fairseq because these package versions have conflicting dependencies.

The conflict is caused by:
    fairseq 0.12.2 depends on omegaconf<2.1
    hydra-core 1.0.7 depends on omegaconf<2.1 and >=2.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by coffeecodeconverter** [comment]
can someone just release a portable version of this? 
or anyone who's got it working (by some MIRACLE) please just make that a portable environment and upload it? 
because the amount of time lost troubleshooting this installation is off the chain. 
95 installs, 1  thing conflicts. you correct the conflict, something else breaks, and round and round you go. 

either that, or explicitly state a full, exhaustive list of everything used, every bit of the config, every version.

**Comment by coffeecodeconverter** [comment]
> Can you try numpy==1.24.3 in requirement.txt. Works for me. But i think you have Python >3.11, you absolutely need 3.10 max ( because of the setuptools drama) app.py will not run in 3.11+

how does numpy 1.24.3 work for you, when "tts 0.21.1 depends on numpy==1.22.0" ? 
this conflicts for me

**Comment by N3M3RU** [comment]
Here's what worked for me. It's a bit rough but hey.
1.  Download the portable version of xtts-web ui by daswer123 " https://huggingface.co/daswer123/xtts_portable/resolve/main/xtts-webui-v1_0-portable.zip?download=true"
2. Copy the contents of the folder "xtts-webui-v1_0-portable\webui\venv\Lib\site-packages"
3. Paste on "XTTS-RVC-UI\venv\Lib\site-packages" and replace all duplicates
4. call start.bat
5. pip install gradio (on venv)
6. call start.bat
7. pip install fairseq (on venv)
8. python app.py (on venv)

Hope it will work for you
