### ISSUE TITLE
Incomplet WebUI

### ISSUE THREAD

**Issue by Ornichus** [Vali-98/XTTS-RVC-UI#9]
### Description:
I encountered an error while installing the packages from requirements.txt. The installation process fails specifically when trying to install the jamo package.

### Steps to Reproduce:
Clone the XTTS-RVC-UI repository.
Create a new virtual environment.
Activate the virtual environment.
Run pip install -r requirements.txt.

### Expected Behavior:
All packages listed in requirements.txt, including jamo, should be installed successfully without any errors.
Actual Behavior:
The installation process fails with an error when trying to install the jamo package. The error message indicates a UnicodeDecodeError while decoding the long_description in the setup.py file of the jamo package.

### Error Message:
```
Copy code  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Erater\AppData\Local\Temp\pip-install-ar579h5m\jamo_e0714986d64243ed8ddb467868cc1551\setup.py", line 11, in <module>
          long_description = f.read()
        File "C:\Users\Erater\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 707: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
### Environment:

Operating System: Windows
Python Version: 3.10.14
pip Version: 24.0

### Additional Context:
I have created a new virtual environment and activated it before running the pip install -r requirements.txt command. The error occurs specifically with the jamo package, while other packages seem to install without issues.
Please advise on how to resolve this installation error with the jamo package. Let me know if you need any further information or details.

**Comment by Ornichus** [comment]
### **UPDATE:**

### Description:
I have successfully installed XTTS-RVC using a conda environment and followed the suggestions provided by a user in another issue post (https://github.com/Vali-98/XTTS-RVC-UI/issues/8#issuecomment-2105660181). However, after launching the application, the UI appears to be different from what is expected. I am missing tabs and only see a few options on the screen.

### Steps to Reproduce:
Created a conda environment for the project.
Modified the start.bat file to activate the conda environment instead of using a Python virtual environment.
Installed the dependencies using the following requirements.txt file:
codefaiss_cpu==1.7.4
gradio==4.7.1
librosa==0.10.0
numpy==1.22.0
praat-parselmouth
pyworld==0.3.4
Requests==2.31.0
scipy==1.11.4
torch==2.1.0
torchcrepe==0.0.22
TTS==0.21.1

Installed fairseq==0.12.2 separately as it was missing from the above requirements.

Launched the application using the modified start.bat file:
batchCopy code@echo off
call conda activate venv
python app.py
pause

### Expected Behavior:
The XTTS-RVC-UI application should launch with the correct UI layout, including all the necessary tabs and options.
Actual Behavior:
The UI of the XTTS-RVC-UI application is incorrect. Tabs are missing, and only a few options are visible on the screen. _(see attached image)_

### Output:
The following output is observed when launching the application:
```
2024-05-11 17:32:42 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2024-05-11 17:32:43 | INFO | faiss.loader | Loading faiss with AVX2 support.
2024-05-11 17:32:43 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2024-05-11 17:32:43 | INFO | faiss.loader | Loading faiss.
2024-05-11 17:32:43 | INFO | faiss.loader | Successfully loaded faiss.
Downloadinghubert_base.pt
Downloadingrmvpe.pt
Downloading vocab.json
Downloading config.json
Downloading dvae.path
Downloading mel_stats.pth
Downloading model.pth
Device: cpu
No supported N-card found, use CPU for inference
2024-05-11 17:34:11 | INFO | fairseq.tasks.hubert_pretraining | current directory is C:\AI\XTTS\XTTS-RVC-UI
2024-05-11 17:34:11 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2024-05-11 17:34:11 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] 4 + [(512,2,2)] 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
C:\Users\Erater\anaconda3\envs\venv\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
> Using model: xtts
[]
[]
C:\Users\Erater\anaconda3\envs\venv\lib\site-packages\gradio\components\dropdown.py:163: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: or set allow_custom_value=True.
warnings.warn(
Running on local URL: http://0.0.0.0:5000/
IMPORTANT: You are using gradio version 4.7.1, however version 4.29.0 is available, please upgrade.
```
I have installed tensorboardX as suggested in the output, but the UI issue persists.

The following output is observed when launching the application again:

```
2024-05-11 18:01:24 | INFO | faiss.loader | Loading faiss with AVX2 support.
2024-05-11 18:01:24 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2024-05-11 18:01:24 | INFO | faiss.loader | Loading faiss.
2024-05-11 18:01:24 | INFO | faiss.loader | Successfully loaded faiss.
Device: cpu
No supported N-card found, use CPU for inference
2024-05-11 18:01:24 | INFO | fairseq.tasks.hubert_pretraining | current directory is C:\AI\XTTS\XTTS-RVC-UI
2024-05-11 18:01:24 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2024-05-11 18:01:24 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
C:\Users\Erater\anaconda3\envs\venv\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
 > Using model: xtts
[]
[]
C:\Users\Erater\anaconda3\envs\venv\lib\site-packages\gradio\components\dropdown.py:163: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
  warnings.warn(
Running on local URL:  http://0.0.0.0:5000
IMPORTANT: You are using gradio version 4.7.1, however version 4.29.0 is available, please upgrade.
--------

```

### Additional Information:

The conda environment is activated correctly, and the application launches without any errors.

Package installed in the venv :

```
Package                   Version
------------------------- -----------
absl-py                   2.1.0
aiofiles                  23.2.1
aiohttp                   3.9.5
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.6.0
antlr4-python3-runtime    4.8
anyascii                  0.3.2
anyio                     4.3.0
async-timeout             4.0.3
attrs                     23.2.0
audioread                 3.0.1
Babel                     2.15.0
bangla                    0.0.2
bitarray                  2.9.2
blinker                   1.8.2
blis                      0.7.11
bnnumerizer               0.0.2
bnunicodenormalizer       0.1.6
catalogue                 2.0.10
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
cloudpathlib              0.16.0
colorama                  0.4.6
confection                0.1.4
contourpy                 1.2.1
coqpit                    0.0.17
cycler                    0.12.1
cymem                     2.0.8
Cython                    3.0.10
dateparser                1.1.8
decorator                 5.1.1
docopt                    0.6.2
einops                    0.8.0
encodec                   0.1.1
exceptiongroup            1.2.1
fairseq                   0.12.2
faiss-cpu                 1.7.4
fastapi                   0.110.3
ffmpy                     0.3.2
filelock                  3.14.0
Flask                     3.0.3
fonttools                 4.51.0
frozenlist                1.4.1
fsspec                    2024.3.1
g2pkk                     0.1.2
gradio                    4.7.1
gradio_client             0.7.0
grpcio                    1.63.0
gruut                     2.2.3
gruut-ipa                 0.13.0
gruut_lang_de             2.0.0
gruut_lang_en             2.0.0
gruut_lang_es             2.0.0
gruut_lang_fr             2.0.2
h11                       0.14.0
hangul-romanize           0.1.0
httpcore                  1.0.5
httpx                     0.27.0
huggingface-hub           0.23.0
hydra-core                1.0.7
idna                      3.7
importlib_resources       6.4.0
inflect                   7.2.1
itsdangerous              2.2.0
jamo                      0.4.1
jieba                     0.42.1
Jinja2                    3.1.4
joblib                    1.4.2
jsonlines                 1.2.0
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
langcodes                 3.4.0
language_data             1.2.0
lazy_loader               0.4
librosa                   0.10.0
llvmlite                  0.42.0
lxml                      5.2.1
marisa-trie               1.1.1
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.8.4
mdurl                     0.1.2
more-itertools            10.2.0
mpmath                    1.3.0
msgpack                   1.0.8
multidict                 6.0.5
murmurhash                1.0.10
networkx                  2.8.8
nltk                      3.8.1
num2words                 0.5.13
numba                     0.59.1
numpy                     1.22.0
omegaconf                 2.0.6
orjson                    3.10.3
packaging                 24.0
pandas                    1.5.3
pillow                    10.3.0
pip                       24.0
platformdirs              4.2.1
pooch                     1.8.1
portalocker               2.8.2
praat-parselmouth         0.4.3
preshed                   3.0.9
protobuf                  5.26.1
psutil                    5.9.8
pycparser                 2.22
pydantic                  2.7.1
pydantic_core             2.18.2
pydub                     0.25.1
Pygments                  2.18.0
pynndescent               0.5.12
pyparsing                 3.1.2
pypinyin                  0.51.0
pysbd                     0.3.4
python-crfsuite           0.9.10
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytz                      2024.1
pywin32                   306
pyworld                   0.3.4
PyYAML                    6.0.1
referencing               0.35.1
regex                     2024.5.10
requests                  2.31.0
resampy                   0.4.3
rich                      13.7.1
rpds-py                   0.18.1
sacrebleu                 2.4.2
safetensors               0.4.3
scikit-learn              1.4.2
scipy                     1.11.4
semantic-version          2.10.0
setuptools                69.5.1
shellingham               1.5.4
six                       1.16.0
smart-open                6.4.0
sniffio                   1.3.1
soundfile                 0.12.1
soxr                      0.3.7
spacy                     3.7.4
spacy-legacy              3.0.12
spacy-loggers             1.0.5
srsly                     2.4.8
starlette                 0.37.2
SudachiDict-core          20240409
SudachiPy                 0.6.8
sympy                     1.12
tabulate                  0.9.0
tensorboard               2.16.2
tensorboard-data-server   0.7.2
tensorboardX              2.6.2.2
thinc                     8.2.3
threadpoolctl             3.5.0
tokenizers                0.19.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.1.0
torchaudio                2.1.0
torchcrepe                0.0.22
tqdm                      4.66.4
trainer                   0.0.36
transformers              4.40.2
TTS                       0.21.1
typeguard                 4.2.1
typer                     0.9.4
typing_extensions         4.11.0
tzdata                    2024.1
tzlocal                   5.2
umap-learn                0.5.6
Unidecode                 1.3.8
urllib3                   2.2.1
uvicorn                   0.29.0
wasabi                    1.1.2
weasel                    0.3.4
websockets                11.0.3
Werkzeug                  3.0.3
wheel                     0.43.0
yarl                      1.9.4
```
Directory files:
```

11/05/2024  17:32    <DIR>          .
11/05/2024  17:32    <DIR>          ..
11/05/2024  17:07                46 .gitignore
11/05/2024  17:07             5 515 app.py
11/05/2024  17:07    <DIR>          infer_pack
11/05/2024  17:07             1 085 LICENSE
11/05/2024  17:33    <DIR>          models
11/05/2024  17:07             1 183 README.md
11/05/2024  17:31               196 requirements.txt
11/05/2024  17:07            14 966 rmvpe.py
11/05/2024  17:07             4 685 rvc.py
11/05/2024  17:32    <DIR>          rvcs
11/05/2024  17:32                57 start.bat
11/05/2024  17:07                14 start.sh
11/05/2024  17:07            23 961 vc_infer_pipeline.py
11/05/2024  17:32    <DIR>          voices
11/05/2024  17:32    <DIR>          __pycache__

```
I have followed the installation steps provided by a user in the previous issue post _(https://github.com/Vali-98/XTTS-RVC-UI/issues/8#issuecomment-2105660181)_.

Please advise on how to resolve the UI issue and ensure that the XTTS-RVC-UI application displays the correct layout with all the necessary tabs and options. Let me know if you require any further information or details.

**My Webui :**
![My XTTS RVC WebUI](https://github.com/Vali-98/XTTS-RVC-UI/assets/67703380/5b30dcd6-bb89-4577-ae1d-e148425b234a)

**How it should look like :**
![How it should look like](https://github.com/Vali-98/XTTS-RVC-UI/assets/67703380/e4b22d4e-76ae-4000-b831-aaea8e0297a6)

**Comment by Vali-98** [comment]
The provided image of the RVC-UI is a different project, and I am not sure what it is.
